In [2]:
import pandas as pd

pd.read_csv("database.csv")

,Unnamed: 0,filename,text,prob,category,bola,health,lifestyle,news,otomotif,teknologi
0,0,lifestyle0.txt,"Speedmaster Moonswatch, Kolaborasi Nyeleneh Om...",[1.6985006e-06 6.4834021e-06 9.9993324e-01 1.8...,lifestyle,0.000002,0.000006,0.999933,1.888433e-07,0.000013,0.000046
1,1,news0.txt,Keluarga Surati Kapolri soal Kasus Kematian Ak...,[1.0801266e-05 1.2002160e-06 3.1746382e-05 9.9...,news,0.000011,0.000001,0.000032,9.999170e-01,0.000009,0.000031
2,2,otomotif0.txt,"Yamaha XSR 155 Custom, Big Wheels Bike\nYOGYAK...",[1.3465828e-05 1.2193529e-05 3.9700029e-05 2.7...,otomotif,0.000013,0.000012,0.000040,2.787099e-05,0.999900,0.000006
3,3,teknologi0.txt,Cara Transfer GoPay ke ShopeePay dengan Mudah ...,[2.2514751e-03 1.3502655e-04 9.3695091e-04 5.6...,teknologi,0.002251,0.000135,0.000937,5.609830e-04,0.005249,0.990866